### ISSUE TITLE
results in shadows

### ISSUE THREAD

**Issue by Jee-King** [dmarnerides/hdr-expandnet#2]
Hi，Why are shadows appearing in the test results?（as shown below）
I didn't find the reason for the shadow in the codes. Thanks in advance!
![test_indoor](https://user-images.githubusercontent.com/24266511/46996390-0f0e0a00-d14f-11e8-9c94-2572617b06e2.png)

**Comment by dmarnerides** [comment]
Hey,  what do you mean by shadows? Is it the band on the right and bottom? Also, can you include your input image?

**Comment by Jee-King** [comment]
Hi, thank you for your reply.
The shadow I said means that the square inside looks darker.
**input**   ![00999999-4-inputs 1](https://user-images.githubusercontent.com/24266511/46997725-028bb080-d153-11e8-904a-953129d2e92c.png)

**output** ![test_indoor](https://user-images.githubusercontent.com/24266511/46997730-04557400-d153-11e8-84a7-8241c3aa7e11.png)

**Comment by dmarnerides** [comment]
Hm.. I just ran it and the .hdr output looks fine. Did you use any other arguments when you ran it?

**Comment by dmarnerides** [comment]
This is the (reinhard) tone mapped prediction I get. 

![prediction_reinhard](https://user-images.githubusercontent.com/7605917/46998147-a193b680-d119-11e8-83ab-2ff5a5d28c3e.jpg)

Which version of PyTorch are you using?

**Comment by Jee-King** [comment]
I did not use other arguments.  I run this code according to the Readme, and the instruction is _python expand.py  ldr_input.jpg_
And  I am using the version of PyTorch is 0.3.1

**Comment by dmarnerides** [comment]
This is weird. I am using version '1.0.0a0+bcb62cb' of PyTorch but things shouldn't be any different for torch > 0.3.

How are you creating the tone mapped version of the prediction that you attach here?

**Comment by Jee-King** [comment]
I think this problem has nothing to do with the tone mapping operator.
I tried the function tonemap in MATLAB, and there will still be obvious boundaries(as shown below).
![tone1](https://user-images.githubusercontent.com/24266511/47000914-ed674f80-d15b-11e8-8d38-3ccf572334cb.png)

**Comment by dmarnerides** [comment]
I just installed a new environment with PyTorch 0.3.1 and I couldn't reproduce the problem. Have you tried rerunning it? It kinda looks like the operation was stopped midway.

**Comment by Jee-King** [comment]
Thank you very much, you are an enthusiastic person！！
I used _pip install OpenCV_ not _conda install opencv -c menpo_. Does this have an impact on results?

**Comment by dmarnerides** [comment]
No worries. Yeah that could cause some problems but I don't think that that's the problem in this case. Can you reproduce this effect if you run it for a second time?

**Comment by Jee-King** [comment]
I ran it for a second time and tested other inputs. It still has problem with  boundaries.
input 
![00999999-5-inputs](https://user-images.githubusercontent.com/24266511/47005211-d88fb980-d165-11e8-9a4b-f1a5ce2e3bc8.png)
output 
![indoor2](https://user-images.githubusercontent.com/24266511/47005249-e8a79900-d165-11e8-9461-d7a2d8d903fa.png)


input
![00999999-6-inputs](https://user-images.githubusercontent.com/24266511/47005278-fceb9600-d165-11e8-8795-78009e3458fc.png)

output
![indoor3](https://user-images.githubusercontent.com/24266511/47005266-f3622e00-d165-11e8-91f8-a32a1eafa121.png)

**Comment by dmarnerides** [comment]
does the problem remain if you use a different patch size?
e.g.
`python expand.py img.jpg --patch_size 128`

**Comment by Jee-King** [comment]
It seems smaller
![55](https://user-images.githubusercontent.com/24266511/47005841-37a1fe00-d167-11e8-88a0-f7aebc429471.png)

**Comment by dmarnerides** [comment]
It looks like there might be a bug with the patch indexing, I'll try and reproduce it/figure it out some time later today.

**Comment by dmarnerides** [comment]
In the meantime, can you email me the actual images you are using as inputs? There might be some downsampling going on in the ones attached here. Or jist let me know the original dimensions

**Comment by Jee-King** [comment]
Ok. Thanks again.

**Comment by dmarnerides** [comment]
Hey, I managed to reproduce the effect and i think i fixed it. Can you please try again and let me know?

**Comment by Jee-King** [comment]
The boundary still exists.
And I use python2.7 which not support   _print(,end='')_, but it will not affect the results.

**Comment by dmarnerides** [comment]
Hey, you should have opened with that :). Python 2.7 was not supported, but you are right, it wasn't mentioned anywhere.

I managed to reproduce exactly what you had in a Python 2.7 environment. The problem was division (and printing). I added the imports and it should work now. Please let me know.

**Comment by Jee-King** [comment]
Hi, It works now！ Thank you very much! 
So the problem was division because of python vision.
Thanks again！
(reinhard)
![indoor1_prediction_reinhard](https://user-images.githubusercontent.com/24266511/47071699-c590ee00-d226-11e8-859d-7bb97dc1307b.jpg)

**Comment by dmarnerides** [comment]
No worries, glad to help!
